name: m31
channels:
  - conda-forge
  - pkgs/main
dependencies:
  - annotated-types=0.6.0=py311hecd8cb5_0
  - aom=3.6.0=hcec6c5f_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.4=py311hecd8cb5_0
  - arrow-cpp=19.0.0=hb704434_4
  - asttokens=3.0.0=py311hecd8cb5_0
  - aws-c-auth=0.9.0=h46256e1_1
  - aws-c-cal=0.9.2=h46256e1_0
  - aws-c-common=0.12.3=h46256e1_0
  - aws-c-compression=0.3.1=h46256e1_1
  - aws-c-event-stream=0.5.5=h46256e1_0
  - aws-c-http=0.10.2=h46256e1_0
  - aws-c-io=0.20.1=h46256e1_0
  - aws-c-mqtt=0.13.2=he61ece7_0
  - aws-c-s3=0.8.3=h46256e1_0
  - aws-c-sdkutils=0.2.4=h46256e1_0
  - aws-checksums=0.2.7=h46256e1_0
  - aws-crt-cpp=0.32.10=h6d0c2b6_0
  - aws-sdk-cpp=1.11.528=he026a02_1
  - blas=1.0=openblas
  - boost-cpp=1.82.0=ha357a0b_2
  - bottleneck=1.4.2=py311h9b7fc35_0
  - brotli-python=1.0.9=py311h6d0c2b6_9
  - brotlicffi=1.0.9.2=py311h6d0c2b6_1
  - bzip2=1.0.8=h6c40b1e_6
  - c-ares=1.19.1=h6c40b1e_0
  - ca-certificates=2025.7.15=hecd8cb5_0
  - cached-property=2.0.1=py311hecd8cb5_0
  - cairo=1.16.0=h08824b9_6
  - certifi=2025.8.3=py311hecd8cb5_0
  - cffi=1.17.1=py311h9205ec4_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py311hecd8cb5_0
  - comm=0.2.1=py311hecd8cb5_0
  - contourpy=1.3.1=py311h1962661_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h6c40b1e_0
  - debugpy=1.8.11=py311h6d0c2b6_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - deprecated=1.2.13=py311hecd8cb5_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - ecos=2.0.14=py311hbc138da_0
  - eigen=3.4.0=ha357a0b_0
  - eval_type_backport=0.3.0=pyha770c72_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6d0c2b6_0
  - feather-format=0.4.1=pyhd8ed1ab_1
  - fftw=3.3.10=nompi_h4fa670e_106
  - filelock=3.17.0=py311hecd8cb5_0
  - fontconfig=2.14.1=h269ac6a_3
  - fonttools=4.55.3=py311h46256e1_0
  - freetype=2.13.3=h02243ff_0
  - fribidi=1.0.10=haf1e3a3_0
  - fsspec=2025.7.0=py311he13d532_0
  - gettext=0.21.0=h4e8c18a_2
  - gflags=2.2.2=hcec6c5f_1
  - gitdb=4.0.12=py311hecd8cb5_0
  - gitpython=3.1.43=py311hecd8cb5_0
  - glog=0.5.0=hcec6c5f_1
  - gmp=6.3.0=h6d0c2b6_0
  - gmpy2=2.2.1=py311h2cec913_0
  - graphite2=1.3.14=he9d5cce_1
  - h5py=3.8.0=nompi_py311h777de7a_100
  - harfbuzz=10.2.0=h060d35a_1
  - hdf5=1.12.2=nompi_h48135f9_101
  - icu=73.1=hcec6c5f_0
  - idna=3.7=py311hecd8cb5_0
  - importlib-metadata=8.5.0=py311hecd8cb5_0
  - importlib_resources=6.4.0=py311hecd8cb5_0
  - inflate64=0.3.1=py311h46256e1_2
  - ipykernel=6.29.5=py311hecd8cb5_1
  - ipython=9.1.0=py311hecd8cb5_0
  - ipython_pygments_lexers=1.1.1=py311hecd8cb5_0
  - itk=5.3.0=py311h9bdd199_1
  - jedi=0.19.2=py311hecd8cb5_0
  - jinja2=3.1.6=py311hecd8cb5_0
  - joblib=1.5.1=py311hecd8cb5_0
  - jpeg=9e=h46256e1_3
  - jupyter_client=8.6.3=py311hecd8cb5_0
  - jupyter_core=5.8.1=py311hecd8cb5_0
  - kiwisolver=1.4.8=py311h6d0c2b6_0
  - lcms2=2.12=hf1fd2bf_0
  - lerc=4.0.0=h6d0c2b6_0
  - libabseil=20250127.0=cxx17_h548131f_0
  - libaec=1.1.3=h6d0c2b6_0
  - libavif=1.1.1=h46256e1_0
  - libboost=1.82.0=hf53b9f2_2
  - libbrotlicommon=1.0.9=h46256e1_9
  - libbrotlidec=1.0.9=h46256e1_9
  - libbrotlienc=1.0.9=h46256e1_9
  - libcurl=8.14.1=h1448931_1
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.14=hb7f2c08_0
  - libev=4.33=h9ed2024_1
  - libevent=2.1.12=h04015c4_1
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libglib=2.84.2=heb90364_0
  - libgrpc=1.71.0=hf2926fd_0
  - libiconv=1.16=h6c40b1e_3
  - libitk=5.3.0=h10ab89a_0
  - libnghttp2=1.57.0=h9beae6a_0
  - libopenblas=0.3.29=h3f8574a_0
  - libosqp=0.6.3=hcec6c5f_0
  - libpng=1.6.39=h6c40b1e_0
  - libprotobuf=5.29.3=h66a43dd_1
  - libqdldl=0.1.7=hcec6c5f_0
  - libre2-11=2024.07.02=hab2016f_0
  - libsodium=1.0.18=h1de35cc_0
  - libssh2=1.11.1=h3a17b82_0
  - libthrift=0.15.0=h70b4b81_2
  - libtiff=4.4.0=h6268bbc_5
  - libtorch=2.6.0=cpu_openblas_h4faba3d_6
  - libuv=1.48.0=h46256e1_0
  - libwebp-base=1.3.2=h46256e1_1
  - libxml2=2.13.8=h6070cd6_0
  - libzlib=1.2.13=h87427d6_6
  - lightning-utilities=0.11.9=py311hecd8cb5_0
  - llvm-openmp=19.1.7=h5048363_2
  - llvmlite=0.44.0=py311hfa5e528_1
  - lz4-c=1.9.4=hcec6c5f_1
  - markupsafe=3.0.2=py311h46256e1_0
  - matplotlib=3.10.0=py311hecd8cb5_0
  - matplotlib-base=3.10.0=py311h919b35b_0
  - matplotlib-inline=0.1.6=py311hecd8cb5_0
  - monai=1.5.1=pyhd8ed1ab_0
  - mpc=1.3.1=h46256e1_0
  - mpfr=4.2.1=h46256e1_0
  - mpmath=1.3.0=py311hecd8cb5_0
  - multivolumefile=0.2.3=pyhd3eb1b0_0
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=py311hecd8cb5_0
  - networkx=3.4.2=py311hecd8cb5_0
  - nibabel=5.3.2=pyha770c72_1
  - nomkl=3.0=0
  - numba=0.61.0=py311h5322ac9_1
  - numexpr=2.11.0=py311h20bc273_0
  - numpy=1.26.4=py311h91b6869_0
  - numpy-base=1.26.4=py311hb3ec012_0
  - openjpeg=2.4.0=h7231236_2
  - openssl=3.0.17=hee2dfae_0
  - opentelemetry-api=1.30.0=py311hecd8cb5_0
  - orc=2.1.1=h4dda5a6_0
  - osqp=0.6.7.post3=py311hfa704c0_1
  - packaging=25.0=py311hecd8cb5_0
  - pandas=2.3.1=py311hebe84f7_0
  - parso=0.8.4=py311hecd8cb5_0
  - patsy=1.0.1=py311hecd8cb5_0
  - pcre2=10.42=h9b97e30_1
  - pexpect=4.9.0=py311hecd8cb5_0
  - pillow=11.0.0=py311h9c91434_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=hb254d66_0
  - platformdirs=4.3.7=py311hecd8cb5_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - protobuf=5.29.3=py311h8d5cf9e_0
  - psutil=5.9.0=py311h46256e1_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py7zr=0.20.5=py311hecd8cb5_0
  - pyarrow=19.0.0=py311h6d0c2b6_1
  - pybcj=1.0.1=py311h46256e1_2
  - pycox=0.3.0=pyhd8ed1ab_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pycryptodomex=3.21.0=py311h46256e1_1
  - pydantic=2.11.7=py311hecd8cb5_0
  - pydantic-core=2.33.2=py311hb0c8e1d_0
  - pygments=2.19.1=py311hecd8cb5_0
  - pyparsing=3.2.0=py311hecd8cb5_0
  - pyppmd=1.0.0=py311hcec6c5f_0
  - pysocks=1.7.1=py311hecd8cb5_0
  - python=3.11.13=hbff2529_0
  - python-dateutil=2.9.0post0=py311hecd8cb5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytorch=2.6.0=cpu_openblas_py311hfcfd596_6
  - pytz=2025.2=py311hecd8cb5_0
  - pyyaml=6.0.2=py311h46256e1_0
  - pyzmq=26.2.0=py311h6d0c2b6_0
  - pyzstd=0.16.2=py311h46256e1_0
  - qdldl-python=0.1.7.post5=np20py311h11d2722_1
  - re2=2024.07.02=h1962661_0
  - readline=8.3=h49f2429_0
  - requests=2.32.4=py311hecd8cb5_0
  - scikit-learn=1.7.1=py311h20cdf89_0
  - scikit-survival=0.25.0=np2py311h26878cd_0
  - scipy=1.16.0=py311hcd1e4c7_0
  - seaborn=0.13.2=py311hecd8cb5_3
  - sentry-sdk=2.18.0=py311hecd8cb5_0
  - setproctitle=1.3.6=py311hc8b0dd6_0
  - setuptools=78.1.1=py311hecd8cb5_0
  - simpleitk=2.2.1=py311h937352e_1
  - six=1.17.0=py311hecd8cb5_0
  - sleef=3.5.1=h6c40b1e_2
  - smmap=5.0.2=py311hecd8cb5_0
  - snappy=1.2.1=h6d0c2b6_0
  - sqlite=3.50.2=hc8b0dd6_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.5=py311hbc138da_0
  - sympy=1.13.3=py311hecd8cb5_1
  - tbb=2022.0.0=h1962661_0
  - texttable=1.6.4=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=py311h85bffb1_0
  - tk=8.6.15=h3a5a201_0
  - torchmetrics=1.4.0.post0=py311hecd8cb5_0
  - torchsurv=0.1.5=pyhd8ed1ab_0
  - torchtuples=0.2.2=pyhd8ed1ab_1
  - tornado=6.5.1=py311h46256e1_0
  - traitlets=5.14.3=py311hecd8cb5_0
  - typing=3.10.0.0=py311hecd8cb5_0
  - typing-extensions=4.12.2=py311hecd8cb5_0
  - typing-inspection=0.4.0=py311hecd8cb5_0
  - typing_extensions=4.12.2=py311hecd8cb5_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py311h46256e1_1
  - urllib3=2.5.0=py311hecd8cb5_0
  - utf8proc=2.6.1=h6c40b1e_1
  - wandb=0.22.3=py311h429a133_0
  - wcwidth=0.2.13=py311hecd8cb5_0
  - wheel=0.45.1=py311hecd8cb5_0
  - wrapt=1.17.0=py311h46256e1_0
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.5=hcec6c5f_0
  - zipp=3.21.0=py311hecd8cb5_0
  - zlib=1.2.13=h87427d6_6
  - zstd=1.5.6=h138b38a_0
